version: "3.7"
services:
  tud-covid19-tracker:
    image: tud7/tud-covid19-tracker:latest
    container_name: tud-covid19-tracker
    ports:
      - "80:8050"
    networks:
      - tud-net
    restart: unless-stopped
  redis:
    image: "redis:alpine"
    networks:
      tud-net:

networks:
  tud-net:
