#!/bin/bash

LOGFILE=cronjob.log
CONTAINER_NAME=tud-covid19-tracker

ERROR=$(docker restart $CONTAINER_NAME 2>&1 > /dev/null)

if [ $? -eq 0 ]
then
  echo "`date`: INFO: $CONTAINER_NAME container restarted" >> $LOGFILE
  exit 0
else
  echo "`date`: ERROR: $CONTAINER_NAME container failed to restart ($ERROR)" >> $LOGFILE
  exit 1
fi

