#!/bin/bash

ERROR=$(docker restart tud-covid19-tracker 2>&1 > /dev/null)

if [ $? -eq 0 ]
then
  echo "`date`: INFO: $container_name container restarted"
  exit 0
else
  echo "`date`: ERROR: $container_name container failed to restart ($ERROR)"
  exit 1
fi

